name: taste_of_perm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.2+1
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true

